spring:
  datasource:
    url: jdbc:mysql://root:r3XMIud20YNsbvlCXbDw@containers-us-west-199.railway.app:6254/railway
    username: root
    password: r3XMIud20YNsbvlCXbDw
  application:
    name: votation-api
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 80
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
